logo:
  subtitle: '黑线条'
  avatar: '[{config.avatar}](/about/)' # you can set avatar link in _config.yml or '[https://xxx.png](/about/)'
  title: '[{config.title}](/)'
open_graph:
  enable: true
  twitter_id: # for open_graph meta
article:
  type: tech # tech/story
  auto_cover: true 
  auto_excerpt: 200
  license: '本文采用 [署名-非商业性使用-相同方式共享 4.0 国际](https://creativecommons.org/licenses/by-nc-sa/4.0/) 许可协议，转载请注明出处。'
  share: [wechat, weibo, email, link]